[CmdletBinding()]
param([string]$Repository=(Get-Location).Path)
$ErrorActionPreference='Stop'
$Repository=(Resolve-Path $Repository).Path
$pattern='(?i)(co-authored-by:.*(bot|qwen|model)|ai[- ]generated|generated by (an ai|a model|qwen)|created with (ai|qwen)|automated authorship)'
$failures=@()
$sourceFiles = @(& git -C $Repository ls-files -co --exclude-standard)
if ($LASTEXITCODE -ne 0) { throw 'Git could not enumerate release source files.' }
$sourceFiles | Where-Object {
    $_ -notmatch '^(?:\.forge-codex|\.forge-qwen|out|build|artifacts|packages)/' -and
    [IO.Path]::GetFileName($_) -ne 'AGENTS.md'
} | ForEach-Object {
    $item = Get-Item -LiteralPath (Join-Path $Repository $_) -ErrorAction SilentlyContinue
    if ($null -eq $item -or $item.PSIsContainer -or $item.Length -ge 4MB) { return }
    $text=Get-Content -Raw -LiteralPath $item.FullName -ErrorAction SilentlyContinue
    if($text -match $pattern){$failures+=$item.FullName}
}
if(Test-Path (Join-Path $Repository '.git')){$log=& git -C $Repository log --format='%H%x09%B' 2>$null;if(($log | Out-String) -match $pattern){$failures+='git-history'}}
if($failures.Count){$failures|Sort-Object -Unique|ForEach-Object{Write-Error $_};throw 'No-attribution gate failed.'}
Write-Host 'No-attribution gate passed.'
