[CmdletBinding()]
param([string]$Repository=(Get-Location).Path)
$ErrorActionPreference='Stop'
$Repository=(Resolve-Path $Repository).Path
$pattern='(?i)(co-authored-by:.*(bot|qwen|model)|ai[- ]generated|generated by (an ai|a model|qwen)|created with (ai|qwen)|automated authorship)'
$failures=@()
Get-ChildItem -LiteralPath $Repository -File -Recurse -Force | Where-Object {$_.FullName -notmatch '\\(\.git|\.forge-inputs|\.forge-qwen|build|out|artifacts|packages)\\' -and $_.Name -ne 'AGENTS.md' -and $_.Length -lt 4MB} | ForEach-Object {$text=Get-Content -Raw -LiteralPath $_.FullName -ErrorAction SilentlyContinue;if($text -match $pattern){$failures+=$_.FullName}}
if(Test-Path (Join-Path $Repository '.git')){$log=& git -C $Repository log --format='%H%x09%B' 2>$null;if(($log | Out-String) -match $pattern){$failures+='git-history'}}
if($failures.Count){$failures|Sort-Object -Unique|ForEach-Object{Write-Error $_};throw 'No-attribution gate failed.'}
Write-Host 'No-attribution gate passed.'
