#pragma once

#include <array>
#include <string_view>

namespace ForgeConductor::Hosts::App {

struct HelpArticle final {
    std::wstring_view title;
    std::wstring_view body;
};

inline constexpr std::array SetupKnowledge{
    HelpArticle{L"Start a project", L"Choose my project folder opens the Windows folder picker. Select the folder containing your work, then Register this project. Registration authorizes that folder and saves a stable project identity; it does not move your files. Instructions and memory are optional. Next, open Provider, discover a loaded model, and test the connection. On Autonomy, describe your task and choose Start managed run."},
    HelpArticle{L"Create a new project folder", L"Use New folder in the Windows folder picker, give it a recognizable name, and select it. An empty folder is a valid starting point. Registration does not create a Git repository or add starter source files. Describe the application you want in the task after setup."},
    HelpArticle{L"Continue an existing project", L"Open Projects and choose the project in Active project. Review Authorized scope to confirm the folder. On Autonomy, use run history to attach to existing work, or describe a new task. Reopening the window does not require registering the same project again."},
    HelpArticle{L"Manager: what it does", L"The Manager is the background process that owns project access, runs, tools, memory, and telemetry. Closing this window does not cancel its work. Use Pause, Resume, or Stop on Autonomy to control a run. If the Manager is disconnected, use its Start or Restart controls and wait for a fresh status before retrying your action."},
    HelpArticle{L"LM Studio: no models found", L"Open LM Studio, download a suitable chat model if needed, load it, and start its local server from the Developer page. Return to Provider and discover models again. Keep the server address and port consistent in both applications. A model being downloaded is not the same as a model being loaded. Downloading a model requires network access and disk space."},
    HelpArticle{L"Provider connection failed", L"Check that LM Studio is running its local server and that Provider has the correct host and port. Save changed provider settings, then test again. A successful connection alone does not prove that the selected model supports tools or context continuation. Use the provider contract check when diagnosing those capabilities. Keep the error text for a support report."},
    HelpArticle{L"Choosing a model", L"Automatic selection uses a compatible loaded model. Choose a specific model when repeatability matters. Large models need more memory and may respond slowly; use LM Studio to inspect available memory and loading errors. Forge Conductor does not make an unloaded model ready merely by selecting its name."},
    HelpArticle{L"First task and native tool access", L"State the desired result, constraints, and how success should be checked. Native tool access is off by default. With it off, the model can respond in text but cannot perform native project work. Enable it deliberately when you want the authorized tools to inspect or change files. Inspect Events & Evidence for actual tool outcomes; a response claiming success is not proof that files changed."},
    HelpArticle{L"Instructions, policy, and governance", L"An instruction package supplies repeatable guidance to new runs. It is not a general policy enforcement engine. Current packages accept a local folder with up to 32 supported text files and 212 KiB of content. A GitHub URL is not a package folder. Prose rules need review, and hard restrictions need Manager checks. Do not treat package activation as proof that every policy requirement was enforced."},
    HelpArticle{L"Validate and activate instructions", L"Choose the project, browse to the package folder, then Validate package. Review the listed files and revision before Activate revision. If files change between validation and activation, validate again. Activation affects new managed runs. Keep unrelated files, archives, and generated output outside the package. Links and reparse points are rejected."},
    HelpArticle{L"Package too large or too many files", L"The current importer reads supported text files recursively. Selecting an entire repository can include archives and duplicate documentation. Prepare a small, deliberate instruction folder and validate its file list. Do not omit mandatory policy documents simply to fit the limit; a larger policy needs a supported intake and retrieval workflow."},
    HelpArticle{L"Project memory", L"Memory keeps durable facts, decisions, and notes under the selected project identity. Use a short title, a useful summary, and details when necessary. Search before adding a duplicate. Instructions describe how to work; memory records what is known. Confirm the selected project before importing, editing, or deleting memory."},
    HelpArticle{L"Pause, stop, and resume", L"Pause requests a pause at a supported execution boundary; it is not an undo operation. Resume continues the exact attached run. Stop cancels further work but does not reverse completed file changes or commands. Read the resulting run state and evidence before starting replacement work."},
    HelpArticle{L"Context continuity", L"Long-running work can approach the model context limit. The Manager coordinates a handoff and successor session while preserving project identity. Inspect continuity status for acknowledgment, errors, and successor progress. A handoff record alone does not prove the successor performed useful work."},
    HelpArticle{L"Tools and permissions", L"Tools are scoped to the authorized project and Manager policy. Choose a capability in Tools to inspect its arguments. Read-only tools inspect; write, Git, and shell tools may change files or repository state. An access-denied result may indicate the wrong project or a path outside its scope. Add the correct project rather than broadening access to unrelated folders."},
    HelpArticle{L"MCP registration", L"LM Studio MCP registration lets LM Studio connect to Forge Conductor tools. It is separate from the model server connection used by managed runs. Inspect the registration first, repair when necessary, and activate it in LM Studio. Primary, fallback, and continuity-control roles serve different purposes; the continuity role intentionally exposes only four tools."},
    HelpArticle{L"Read telemetry correctly", L"Rig shows CPU, RAM, GPU, disk, process, and workflow observations. Missing, stale, or disconnected data is not a zero measurement. GPU support depends on the available counters and hardware. Check timestamps and connection state before interpreting a flat chart. A busy CPU or GPU does not by itself prove useful task progress."},
    HelpArticle{L"Evidence and verified results", L"Events & Evidence associates observations with projects and runs. A native check result proves only the check that ran, for the recorded inputs. Model text, a green connection indicator, and a completed process are different kinds of evidence. Inspect failures and exported logs before calling a feature verified."},
    HelpArticle{L"Settings and recovery", L"Save settings to persist edits; changing a field alone does not necessarily apply it. Some settings require a Manager restart. Use scoped reset controls only after checking the selected scope and preserving needed records. Resetting data is not a routine solution for a provider connection error."},
    HelpArticle{L"Report a problem", L"Record the application version, selected project, action, expected result, actual result, error text, and time. Include relevant run identifiers and exported evidence. Remove credentials and private file contents before sharing logs. State whether the problem happened in the installed application or a development build."},
};

} // namespace ForgeConductor::Hosts::App
