#pragma once

#include <array>
#include <string_view>

namespace ForgeConductor::Hosts::App {

struct HelpArticle final {
    std::wstring_view title;
    std::wstring_view body;
};

inline constexpr std::array SetupKnowledge{
    HelpArticle{L"Start a project automatically", L"Open Guided setup and choose a folder. Forge Conductor starts its Manager, registers the folder, prepares a compatible downloaded model and checks its response. Wait for all four checks to become Ready, describe your task on the same page, review the file and command permission, then choose Start task. If preparation stops, its last check explains what needs attention; Retry reuses completed setup."},
    HelpArticle{L"Create a new project folder", L"Use New folder in the Windows folder picker, give it a recognizable name, and select it. An empty folder is a valid starting point. Registration does not create a Git repository or add starter source files. Describe the application you want in the task after setup."},
    HelpArticle{L"Continue an existing project", L"Open Projects and choose the project in Active project. Review Authorized scope to confirm the folder. On Autonomy, use run history to attach to existing work, or describe a new task. Reopening the window does not require registering the same project again."},
    HelpArticle{L"Manager: what it does", L"The Manager is the background process that owns project access, runs, tools, memory, and telemetry. Closing this window does not cancel its work. Use Pause, Resume, or Stop on Autonomy to control a run. If the Manager is disconnected, use its Start or Restart controls and wait for a fresh status before retrying your action."},
    HelpArticle{L"LM Studio: no models found", L"Preparation starts the installed LM Studio CLI server and loads a downloaded model when possible. If no compatible model is downloaded, use LM Studio to download a tool-capable coding model, then Retry preparation. The model must support the configured context capacity. Downloads use network bandwidth and disk space; preparation does not silently download weights."},
    HelpArticle{L"Provider connection failed", L"Check that LM Studio is running its local server and that Provider has the correct host and port. Save changed provider settings, then test again. A successful connection alone does not prove that the selected model supports tools or context continuation. Use the provider contract check when diagnosing those capabilities. Keep the error text for a support report."},
    HelpArticle{L"Choosing a model", L"Preparation first reuses a compatible loaded model. If no model is pinned in Provider settings, it can load the smallest compatible downloaded model. Tool support and actual loaded context are checked before readiness. A pinned model is respected; clear or change the Provider selection if that model is unavailable. Model size alone does not guarantee good coding results."},
    HelpArticle{L"First task and native tool access", L"State the desired result, constraints, and how success should be checked. Guided setup shows file and project command access next to Start task, enabled for project work. Turn it off for a text-only response. Starting the task authorizes the enabled tools within the selected project, subject to Manager restrictions. Inspect Events & Evidence for actual tool outcomes; model text is not proof that files changed."},
    HelpArticle{L"Import development policy and governance", L"Open Development policy and governance in Guided setup. Paste a GitHub repository URL or local folder, then Import preview. GitHub imports pin an exact commit; private repositories use your existing Git sign-in. Inspect the complete file list and exclusions, then Adopt revision. Adoption blocks write tools and commands until a completed human review records permitted paths and exact commands. New runs can read the pinned documents through project_policy.read."},
    HelpArticle{L"Validate and activate instructions", L"Choose the project, browse to the package folder, then Validate package. Review the listed files and revision before Activate revision. If files change between validation and activation, validate again. Activation affects new managed runs. Keep unrelated files, archives, and generated output outside the package. Links and reparse points are rejected."},
    HelpArticle{L"Policy limits and complete source review", L"The policy importer supports up to 2,048 files, 2 MiB per text file and 16 MiB of text. Unsupported files are listed for explicit review or justified exclusion. Imported scripts are source documents and are never executed by import. Read document and Next part show complete text in bounded pages. The separate instruction-package feature retains its smaller 32-file limit."},
    HelpArticle{L"Project memory", L"Memory keeps durable facts, decisions, and notes under the selected project identity. Use a short title, a useful summary, and details when necessary. Search before adding a duplicate. Instructions describe how to work; memory records what is known. Confirm the selected project before importing, editing, or deleting memory."},
    HelpArticle{L"Pause, stop, and resume", L"Pause requests a pause at a supported execution boundary; it is not an undo operation. Resume continues the exact attached run. Stop cancels further work but does not reverse completed file changes or commands. Read the resulting run state and evidence before starting replacement work."},
    HelpArticle{L"Context continuity", L"Long-running work can approach the model context limit. The Manager coordinates a handoff and successor session while preserving project identity. Inspect continuity status for acknowledgment, errors, and successor progress. A handoff record alone does not prove the successor performed useful work."},
    HelpArticle{L"Tools and permissions", L"Tools are scoped to the authorized project and Manager policy. Choose a capability in Tools to inspect its arguments. Read-only tools inspect; write, Git, and shell tools may change files or repository state. An access-denied result may indicate the wrong project or a path outside its scope. Add the correct project rather than broadening access to unrelated folders."},
    HelpArticle{L"MCP registration", L"LM Studio MCP registration lets LM Studio connect to Forge Conductor tools. It is separate from the model server connection used by managed runs. Inspect the registration first, repair when necessary, and activate it in LM Studio. Primary, fallback, and continuity-control roles serve different purposes; the continuity role intentionally exposes only four tools."},
    HelpArticle{L"Read telemetry correctly", L"Rig shows CPU, RAM, GPU, disk, process, and workflow observations. Missing, stale, or disconnected data is not a zero measurement. GPU support depends on the available counters and hardware. Check timestamps and connection state before interpreting a flat chart. A busy CPU or GPU does not by itself prove useful task progress."},
    HelpArticle{L"Evidence and verified results", L"Events & Evidence associates observations with projects and runs. A native check result proves only the check that ran, for the recorded inputs. Model text, a green connection indicator, and a completed process are different kinds of evidence. Inspect failures and exported logs before calling a feature verified."},
    HelpArticle{L"Settings and recovery", L"Save settings to persist edits; changing a field alone does not necessarily apply it. Some settings require a Manager restart. Use scoped reset controls only after checking the selected scope and preserving needed records. Resetting data is not a routine solution for a provider connection error."},
    HelpArticle{L"Report a problem", L"Record the application version, selected project, action, expected result, actual result, error text, and time. Include relevant run identifiers and exported evidence. Remove credentials and private file contents before sharing logs. State whether the problem happened in the installed application or a development build."},
    HelpArticle{L"What preparation changes", L"Preparation may start the Manager service and LM Studio server, register the chosen folder, load an already downloaded model, and save its verified instance name. It does not move project files, initialize Git, or download model weights. Project and provider settings persist so Retry can continue from existing state."},
    HelpArticle{L"Retry without duplicate projects", L"Use Retry preparation after correcting the reported problem. The Manager resolves the same project folder to its existing identity. A failed model check does not discard the registered project. If you choose a different folder, check the displayed project before starting work."},
    HelpArticle{L"Cancel preparation", L"Cancel stops pending setup work. A project already registered or a server already started remains available. A model load accepted by LM Studio may continue in that application even after the connection is cancelled. Retry reads the current inventory before deciding whether another load is needed."},
    HelpArticle{L"Downloaded versus loaded models", L"A downloaded model is stored on disk. A loaded model has an active inference instance using memory. Preparation checks both inventories and verifies the active instance after loading. Deleting downloaded files is not needed to fix a failed connection."},
    HelpArticle{L"Context capacity is too small", L"Context is the space available for instructions, task history, tool results and the next response. The Manager reserves part of it for continuation and handoff. Preparation requires enough actual loaded context for these settings. Increase the loaded capacity or select another compatible model; changing only its display name does not change its capacity."},
    HelpArticle{L"Model loading is slow", L"Loading a large model can take time and consume substantial memory. Keep the preparation status visible and inspect LM Studio for an allocation error if loading fails. Retry rechecks whether the first load completed. Avoid repeatedly starting additional large models when memory is already constrained."},
    HelpArticle{L"Server authentication error", L"HTTP 401 or 403 means the server rejected access. Preparation does not fix this by starting another server or replacing your security settings. Check the local server authentication configuration and use a supported authenticated connection before retrying."},
    HelpArticle{L"Wrong local server port", L"Provider settings and LM Studio must use the same loopback address and port. Preparation uses the saved address. If no server responds, it can start the installed CLI on that port. A port occupied by another program needs correction in Provider settings; an unrelated service is not a compatible model server."},
    HelpArticle{L"Missing LM Studio CLI", L"Automatic server startup looks for the installed LM Studio CLI in your user profile. Open LM Studio and enable its CLI if setup reports it missing. An already running compatible server can be used without starting the CLI. Retry after installation or startup."},
    HelpArticle{L"The connection check passed but work failed", L"The setup check verifies a short model response. Real project work additionally depends on tool calls, workspace authority, model behavior and task-specific dependencies. Read the first failing event in Autonomy or Events & Evidence, resolve that cause, and then retry the task. Do not infer tool execution from a connection check."},
    HelpArticle{L"Describe a useful first task", L"Start with a small observable result, such as creating a README explaining the current project or inspecting its build instructions. Name the folder scope and the command or file that should demonstrate success. Expand the task after confirming the first result and its evidence."},
    HelpArticle{L"Text-only tasks", L"Turn file and project command access off before Start task when you only want an explanation or plan. The run can return text but cannot carry out file changes through native tools. To implement the plan, start a task with the needed permission enabled."},
    HelpArticle{L"Changed project after preparation", L"Readiness belongs to the project that was prepared. If you select another project elsewhere in the application, return to Guided setup and Retry before using its task button. The application checks project identity again rather than treating an earlier ready state as permission for a different folder."},
    HelpArticle{L"New provider settings and running tasks", L"New runs resolve the saved provider endpoint and model. Existing runs retain their pinned connection, persisted across Manager restart. Preparation selects a model before starting a durable run. A missing model or provider response after restart needs attention; changing settings does not silently migrate an old run."},
    HelpArticle{L"Manager versus model server", L"The Manager owns projects, permissions, run history and tool execution. LM Studio supplies model responses. These are separate processes, and either can be unavailable. Preparation reports them as separate checks so you can identify which part needs attention."},
    HelpArticle{L"Use an empty folder", L"Create a folder in the Windows picker and select it. The Manager can register an empty folder. Describe the application and required platform in the task; setup itself does not choose a language, install packages or generate a project template."},
    HelpArticle{L"Build tools are missing", L"Preparing the model does not install every compiler, SDK or package manager that a project might require. Ask the task to inspect the repository's build requirements and report missing dependencies. A compiler failure should name the missing tool and the command attempted in its evidence."},
    HelpArticle{L"Understand a tool denial", L"A denial prevents that requested operation; it does not undo previous work. Check the selected project, requested path, current authority and adopted policy. Correct the scope or satisfy the stated review requirement. Repeating the same denied request does not broaden permission."},
    HelpArticle{L"Keep setup evidence", L"Record the four setup checks, selected folder, model instance and the first run identifier when validating a machine. Also keep the tool outcomes and task-specific checks. This makes a setup failure distinguishable from a later build or model failure."},
    HelpArticle{L"Close and reopen setup", L"The selected setup folder is saved for the current application profile. On reopening, Retry checks the current Manager and model state before enabling Start task. A saved folder is a convenience, not a cached promise that services are still ready."},
    HelpArticle{L"Record a policy review", L"Read all applicable source documents and resolve their obligations before accepting review. Record your name and the evidence location, allowed project-relative paths, prohibited paths and exact commands. The checkbox is your attestation, never an automatic compliance finding. An empty allowed-path list permits no file edits. Replacing the adopted revision clears its prior review."},
    HelpArticle{L"What policy enforcement proves", L"The Manager enforces the accepted revision, review prerequisite, file path restrictions and exact shell argument matches. It does not prove arbitrary prose, architecture or legal compliance. Approved commands execute with the existing native command controls; they are not a filesystem sandbox. Review the actual command and its scripts before approval. A model cannot accept its own review through the policy reading tool."},
};

} // namespace ForgeConductor::Hosts::App
