[CmdletBinding()]
param([Parameter(Mandatory)][string]$WorkspaceRoot)
$ErrorActionPreference = "Stop"

$patterns = @(
    '(?i)\bAI[- ]generated\b',
    '(?i)\bgenerated by (ChatGPT|OpenAI|Codex|an AI|a model)\b',
    '(?i)\bcreated (with|by) (ChatGPT|OpenAI|Codex|AI)\b',
    '(?i)^Co-authored-by:.*(bot|openai|chatgpt|codex)',
    '(?i)\bautomated authorship\b'
)
$violations = [System.Collections.Generic.List[string]]::new()
Get-ChildItem -LiteralPath $WorkspaceRoot -Recurse -Force -File | ForEach-Object {
    if ($_.Name -eq "AGENTS.md") { return }
    if ($_.FullName -match '\\.git\\|\\.forge-inputs\\|\\.forge-codex\\|\\build\\|\\out\\|\\artifacts\\') { return }
    if ($_.Length -gt 4MB) { return }
    $text = Get-Content -Raw -LiteralPath $_.FullName -ErrorAction SilentlyContinue
    foreach ($pattern in $patterns) {
        if ($text -match $pattern) {
            $violations.Add("$($_.FullName): $pattern")
        }
    }
}
if ($violations.Count) {
    $violations | ForEach-Object { Write-Error $_ }
    throw "No-attribution gate failed."
}
Write-Host "No-attribution gate passed."
